"""
- Reads in the MNIST dataset after PCA (generated by PCA.py)
- Train a SVM based on the first two PCA components
"""

import numpy as np
import h5py
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.metrics import jaccard_score

if __name__ == "__main__":
    folder = Path("data") / "MNIST_PCA4"
    filename_train = folder / "mnist_pca4_train.h5"

    with h5py.File(filename_train, "r") as f:
        X = f["X_pca"][:]
        y = f["y"][:]

    print(X.shape, y.shape)

    # only y = 1 or y = 5
    mask = (y == 1) | (y == 5)
    X = X[mask]
    y = y[mask]
    print(X.shape, y.shape)

    # train a SVM on the first n PCA components
    # 1st component only
    print("Training SVM on first PCA component...")
    svm_model = svm.SVC(kernel="linear")
    svm_model.fit(X[:, :1], y)
    score = svm_model.score(X[:, :1], y)
    print(f"SVM accuracy on first PCA component: {score:.2f}")

    # First two components
    print("Training SVM on first two PCA components...")
    svm_model = svm.SVC(kernel="linear")
    svm_model.fit(X[:, :2], y)
    score = svm_model.score(X[:, :2], y)
    print(f"SVM accuracy on first two PCA components: {score:.2f}")

    # First three components
    print("Training SVM on first three PCA components...")
    svm_model = svm.SVC(kernel="linear")
    svm_model.fit(X[:, :3], y)
    score = svm_model.score(X[:, :3], y)
    print(f"SVM accuracy on first three PCA components: {score:.2f}")

    # First four components
    print("Training SVM on first four PCA components...")
    svm_model = svm.SVC(kernel="linear")
    svm_model.fit(X[:, :4], y)
    score = svm_model.score(X[:, :4], y)
    print(f"SVM accuracy on first four PCA components: {score:.2f}")

    # Training SVM on first PCA component...
    # SVM accuracy on first PCA component: 0.95
    # Training SVM on first two PCA components...
    # SVM accuracy on first two PCA components: 0.96
    # Training SVM on first three PCA components...
    # SVM accuracy on first three PCA components: 0.97
    # Training SVM on first four PCA components...
    # SVM accuracy on first four PCA components: 0.97
